### ISSUE TITLE
Issue for downloading Chemrich results table and pptx file

### ISSUE THREAD

**Issue by xkcococo** [barupal/chemrich#10]
Greetings,

I tried to use this website to generate results, and I cannot download the table and the pptx file.
I also cannot download the files via using the example data.

![image](https://user-images.githubusercontent.com/43758155/129981190-599763e9-bd17-4bf2-9cc9-04377e09f2ff.png)
There is no response after click these two bottoms. 

I was wondering if I could get these two files?
Thanks in advance!

**Comment by barupal** [comment]
The server has been having some issues. 
Can you try the local version available here https://chemrich.idsl.me ?

**Comment by micwij** [comment]
I've been having similar problems. However, downloading the excel table works, if I right click on the button and select "Save as". It still gives me a warning, that it "can't be downloaded securely" but I can select "Keep" and then it is still downloaded. I am not sure if this is related to my browser (Chrome) or security settings by my institution, but maybe this information helps in generally fixing the problem.

**Comment by barupal** [comment]
The web-version is outdated. Please use the r code from this github repo for any chemrich related calculations.
