### ISSUE TITLE
Possibilities for contributing to package development

### ISSUE THREAD

**Issue by lorenzoFabbri** [barupal/chemrich#12]
I am a PhD student in Exposomics and Metabolomics. I got interested in Enrichment Analysis, and I would like to apply ChemRICH in my future papers. I was wondering whether you plan to expand/improve it, and if so whether you are looking for collaborators. Thank you.
@barupal

**Comment by barupal** [comment]
Hi Lorenzo, 
Sure. Can you reach out to me at barupal@gmail.com ? We can schedule a zoom call. 
Dinesh
