### ISSUE TITLE
chemrich_tree labels not included in the output.

### ISSUE THREAD

**Issue by ccshao** [barupal/chemrich#13]
Dear ChemRICH dev,

Thanks very much for this interesting tool.

We are playing with the online version, https://chemrich.fiehnlab.ucdavis.edu/. In the tree plot, the clusters are  labeled with a single character.  However, the branch label are not included in the file "ChemRICH_results.xlsx". 

A small issue is that the x-axis of "chemrich_impact_plot_pptx" is shown as "median XlogP of clusters", shouldn't be "cluster orders in the similarity tree?

**Comment by barupal** [comment]
The online version (https://chemrich.fiehnlab.ucdavis.edu/) cannot be
updated anymore.  You should follow the new instructions at chemrich.idsl.me
site.

**Comment by ccshao** [comment]
@barupal Thanks for the quick reply! 

I have managed to run ChemRICH locally. Currently we are working with lipids data, and I am not sure how to get similar results as we have got with the online verion. 

Previousyl, we have prepared the input for the onlie version as required
```
    Column 1 = Compound Name
    Column 2 = InChiKeys
    Column 3= Pubchem ID
    Column 4 = SMILES
    Column 5 = pvalue
    Column 6= foldchange
```
Online ChemRICH returns us with enrichment for different lipid class, like "lysophospholipids", "Saturated_phosphatidylserines", which are very interesting.

How should we prepare the input file for ChemRICH 2.0 for the lipids data to obtain results similar to v1.0?

Thanks!

**Comment by barupal** [comment]
The input has been simplified. 
Step 1: Predict MeSH classes at https://chemrich.idsl.me/predict-mesh-classes
Step 2: Run ChemRICH for lipids at https://chemrich.idsl.me/run-chemrich/lipids

**Comment by ccshao** [comment]
Thanks and I am able to reproduce the impact plots as online version. 
By the way, I checked the R codes in the repo and didn't find functions to plot the tree structures. Did I miss some parts, or not implemented yet?

**Comment by barupal** [comment]
The tree plot will be added in the next version.

**Comment by ccshao** [comment]
Thanks and the results really provide interesting insights! Looking forward to see the formal version.
