### ISSUE TITLE
Error message while uploading the input file for the ChemRich analysis

### ISSUE THREAD

**Issue by akumar901** [barupal/chemrich#14]
Greetings,

I have followed the instructions provided to generate an input file from [](https://chemr
ich.fiehnlab.ucdavis.edu/). But when I am trying to upload the dataset for the analysis it's giving me two errors (attached). Please provide me with a solution for the issue.

Error 1: Argument 1 is not a vector. 
Erro 2: Must supply an IAtomContainer or something coercable to it

Thank you. 

![Screen Shot 2022-03-18 at 2 50 23 PM](https://user-images.githubusercontent.com/62219024/159083212-3457b494-349c-417f-9e1a-982efa10848e.png)
![Screen Shot 2022-03-18 at 3 30 29 PM](https://user-images.githubusercontent.com/62219024/159083214-cad24cf3-658b-41ff-9a23-68e016f0f6b1.png)

**Comment by barupal** [comment]
Hello Amar, 
First error : one of the SMILES codes is not correct. 
Second error: no signficant cluster was found.

**Comment by akumar901** [comment]
Thank you for the response. Now I am facing another issue after correcting the SMILES code.
![Screen Shot 2022-03-21 at 10 49 40 AM](https://user-images.githubusercontent.com/62219024/159300270-0f2f49a2-99b9-4784-9b0d-283b3a30556b.png)

**Comment by barupal** [comment]
Can you share the input file ?

**Comment by akumar901** [comment]
Thank you for your reply. Sure.
[Test_input_exp.xlsx](https://github.com/barupal/ChemRICH/files/8321529/Test_input_exp.xlsx)

**Comment by akumar901** [comment]
This input file (Test_input_exp.xlsx) when copied and pasted to the ChemRich again showing the same error that says that the SMILES code is wrong but, these SMILES/ InchiKeys etc. codes were all copied and pasted from the Pubchem and its been double checked.

**Comment by barupal** [comment]
Try running it locally - https://chemrich.idsl.me/predict-mesh-classes 
Use the checkSmiles function (bottom of the page) to see which SMILES code is problematic.

**Comment by akumar901** [comment]
Thank you I was able to run the script and figured out that there were 22 wrong SMILES code, which is bit surprising as I have copy and pasted all the SMILES code from PubChem.

**Comment by akumar901** [comment]
Do you have any script to figure out that which specific SMILES code are wrong, so that inspite of going through each code, I just correct the one which are wrong ?

**Comment by barupal** [comment]
The checkSmiles function sould have printed the index of incorrect smiles codes. 
```
checkSmiles <- function(input = "inputfile.xlsx") {
  ndf <- readxl::read_xlsx(input)
  fps <- lapply(1:nrow(ndf), function(x) {
    rcdk::parse.smiles(ndf$smiles[x])
  })
  charvec <- sapply(fps, nchar)
  paste0("Lines with an incorrect SMILES codes are : ", paste(as.integer(which(charvec==4)), collapse = ","))
}
checkSmiles("chemrich_input_mesh_prediction.xlsx")
```
File format : https://github.com/barupal/ChemRICH/blob/master/chemrich_input_mesh_prediction.xlsx?raw=true

**Comment by barupal** [comment]
Since, you are using data from Metabolon, you can use their sub-pathway/super-pathway ontology as set definitions. See more here https://chemrich.idsl.me/run-chemrich/for-metabolons-data

**Comment by akumar901** [comment]
Thank you, Yes, I don't know how I missed that. I got that one and corrected the wrong one. But now when I am running into this error. 

![Screen Shot 2022-03-22 at 2 02 16 PM](https://user-images.githubusercontent.com/62219024/159556215-42c1ccda-d21f-42ae-a173-a3237e0db870.png)

**Comment by akumar901** [comment]
> Since, you are using data from Metabolon, you can use their sub-pathway/super-pathway ontology as set definitions. See more here https://chemrich.idsl.me/run-chemrich/for-metabolons-data

Thank you. I will check this link.

**Comment by barupal** [comment]
> Thank you, Yes, I don't know how I missed that. I got that one and corrected the wrong one. But now when I am running into this error.
> 
> ![Screen Shot 2022-03-22 at 2 02 16 PM](https://user-images.githubusercontent.com/62219024/159556215-42c1ccda-d21f-42ae-a173-a3237e0db870.png)

One of the r-packages was not installed correctly. Try re-installing it. 

```
if (!require("devtools"))
    install.packages('devtools', repos="http://cran.rstudio.com/")
  if (!require("RCurl"))
    install.packages('RCurl', repos="http://cran.rstudio.com/")
  if (!require("pacman"))
    install.packages('pacman', repos="http://cran.rstudio.com/")
  library(devtools)
  library(RCurl)
  library(pacman)
  if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  pacman::p_load(GGally)
  pacman::p_load(DT)
  pacman::p_load(RCurl)
  pacman::p_load(RJSONIO)
  pacman::p_load(ape)
  pacman::p_load(devEMF)
  pacman::p_load(dynamicTreeCut)
  pacman::p_load(extrafont)
  pacman::p_load(ggplot2)
  pacman::p_load(ggpubr)
  pacman::p_load(ggrepel)
  pacman::p_load(grid)
  pacman::p_load(htmlwidgets)
  pacman::p_load(igraph)
  pacman::p_load(magrittr)
  pacman::p_load(network)
  pacman::p_load(officer)
  pacman::p_load(openxlsx)
  pacman::p_load(phytools)
  pacman::p_load(plotly)
  pacman::p_load(plotrix)
  pacman::p_load(rcdk)
  pacman::p_load(readxl)
  pacman::p_load(rvg)
  pacman::p_load(sna)
  pacman::p_load(visNetwork)
```

**Comment by akumar901** [comment]
Dr. @barupal  Thank you for the help. I was able to get rid of all the errors and was able to run ChemRICH both locally as well as on the online version. 

I would like to discuss one more issue, I am right now trying to work with the Cytoscape to identify the relevant connections (closely related metabolites). Although the end clustering results (after Y organic layout and GLAY clustering) were not as expected. Most of the closely related metabolites (like lipids, and amino acids) are scattered far and are connected in a different cluster. 

It would be helpful if you could provide any suggestions for that.

**Comment by barupal** [comment]
How did you create the network graph? Using MetaMapp?

**Comment by akumar901** [comment]
@barupal Yes.

**Comment by barupal** [comment]
Can you share the input xlsx file for MetaMapp ?

**Comment by akumar901** [comment]
Sure.
[test.xlsx](https://github.com/barupal/ChemRICH/files/8523768/test.xlsx)

**Comment by barupal** [comment]
[chemsim_krp_07.sif--clustered.pdf](https://github.com/barupal/ChemRICH/files/8523926/chemsim_krp_07.sif--clustered.pdf)
[test.zip](https://github.com/barupal/ChemRICH/files/8523931/test.zip)

It looks okay. You are actually seeing the sub-clusters within major classes. You can avoid the Glay clustering method to get a more connected graph.

**Comment by akumar901** [comment]
Thank you. I will check it again and will share it with you.

**Comment by akumar901** [comment]
Dr @barupal  

I am getting the same map and cluster (in figure_2) as you got (in figure_1).   My only question is why am I seeing the metabolites of different classes like Alpha tocopherol (a tocopherol) and gamma CEHC ( a dipeptide /Organoheterocyclic compounds) both are related to vit. E.  clustered with the different classes naproxen (a class of cyloparaffins) ? 

![Figure_2](https://user-images.githubusercontent.com/62219024/164315497-525d9a90-cbe1-4ed7-a81a-b41f4c4bf84a.png)
![Figure_1](https://user-images.githubusercontent.com/62219024/164315502-818ad4d1-1461-48e0-baed-f6cedd553772.png)

**Comment by barupal** [comment]
They seem to be part of a large cluster of compounds with at least one benzene ring (aromatics).

**Comment by akumar901** [comment]
Ok, that explains. Thank you.
