### ISSUE TITLE
Different p value thresholds for different columns of ChemRICH basic output file

### ISSUE THREAD

**Issue by Moonbow11** [barupal/chemrich#16]
Hello,

Thanks for everything you do creating and maintaining ChemRICH! It is my favorite metabolite set analysis package and I am very happy to be able to use it through R. I found something confusing in the results file though and wanted to bring it to your attention. For the function run_chemrich_basic you are using a threshold of p < 0.1 to calculate the "Altered Ratio" and the "Increased ratio", but a threshold of p < 0.05 to calculate the columns "Altered metabolites", "Increased" and "Decreased". I am not sure if you did this on purpose or not but it is confusing in the summary results file because it looks like the altered ratio and increased ratio should be able to be calculated from cluster size, altered metabolites, increased and decreased, but actually the numbers are different. I think the threshold of p < 0.1 makes more sense considering you selected the option "greater" for the KS test instead of "two-sided." But I just wanted you to know about this in case you want to change it.

All the best,
Katie Glass

**Comment by barupal** [comment]
Hi Katie,
Thanks for your feedback.  Agree with you on the threshold inconsistency. It has been fixed in all scripts.  We now have 0.05 for all steps.  0.1 was sometimes helpful to pick up borderline sets, but it can be confusing, as you have noticed.
Best,
Dinesh

**Comment by Moonbow11** [comment]
Hi Dinesh,

Thank you again for getting back to me so quickly and making those changes. There is just one more outstanding 0.1 that is leading to an incorrect value for the increased ratio, on line 91 of the chemrich minimum analysis script. 

So line 90-92 is currently:
uprat <-sapply(clusterdf$name, function (k) {
      length(which(ndf$set==k & ndf$pvalue<0.05 & ndf$edirection == "up"))/length(which(ndf$set==k & ndf$pvalue<0.10))
    })

And should be changed to: 
uprat <-sapply(clusterdf$name, function (k) {
      length(which(ndf$set==k & ndf$pvalue<0.05 & ndf$edirection == "up"))/length(which(ndf$set==k & ndf$pvalue<0.05))
    })

Just letting you know and hope you are having a great weekend! 

All the best,
Katie

**Comment by barupal** [comment]
Thanks for catching it. Fixed. 
Great weekend too! 
Dinesh

**Comment by Moonbow11** [comment]
Hi Dinesh, 

Thank you very much for fixing that so quickly, I already have all my updated results now. 

Take care,
Katie
