### ISSUE TITLE
Problem with ChemRICH

### ISSUE THREAD

**Issue by reesese** [barupal/chemrich#2]
Hello, I'm having trouble running ChemRICH on any data, even the example data provided. When I run with my own data I get the below error:
<img width="438" alt="screen shot 2018-06-29 at 2 29 11 pm" src="https://user-images.githubusercontent.com/39413802/42108568-ecde440a-7ba8-11e8-9377-6ab20e9d4517.png">

Even when I attempt to copy in the example data provided, I get the below error:
<img width="392" alt="screen shot 2018-06-29 at 2 31 29 pm" src="https://user-images.githubusercontent.com/39413802/42108651-27e13968-7ba9-11e8-8d85-a3c265bd9a7c.png">

I thought that this might be because of using Chrome, but when I switched to Safari, it said the column names were wrong and to use the ones in the example file...I am using the ones in the example file.

I'd really like to be able to use this tool! Please help!

**Comment by barupal** [comment]
ChemRICH is working with the example data, just tested it. Can you send me your input data file (xlsx) ?

**Comment by TMG73** [comment]
Hello, I have the same problem with copy the example file. Maybe a MAC problem?

**Comment by TMG73** [comment]
The problem is fixed after changing my general settings (US decimal points instead European ,)
Thanks Barupal.
