### ISSUE TITLE
problem with chemrich

### ISSUE THREAD

**Issue by smweston** [barupal/chemrich#3]
Hi there! I am interested in using chemrich for my data, however when I paste my data set I get the following error code: 

Error replacement has 2 rows, data has 0
In call:
`$<-.data.frame`(`*tmp*`,order,value = c(1L, 0L))

My data set attached:

[Codes for ChemRich Analysis_RPD_Pre_Post.xlsx](https://github.com/barupal/chemrich/files/2234316/Codes.for.ChemRich.Analysis_RPD_Pre_Post.xlsx)

Can you let me know what I need to do differently?

Thank you!

**Comment by barupal** [comment]
Fold-changes cannot be negative. Calculate them as median ration between two study groups. It seems that in your study not a single cluster was significant so the tool failed to make the ChemRICH plot.
