### ISSUE TITLE
Inchikey and pubchemID of lipids

### ISSUE THREAD

**Issue by ddkale** [barupal/chemrich#4]
Hi Dinesh 

First of all thank you for the Chemrich software and also many other services provided by you and your team for metabolomics data analysis.

I would like to use Chemrich for my lipidomics dataset. While searching for InChiKey and PubchemCIDs I encountered a question.

I used  http://cts.fiehnlab.ucdavis.edu/ service for identification of InChIKey and                                              PubChem CID of TG   (58:10) ; where I got 5 hits

Chemical   Name | InChIKey                                                    | Score | PubChem CID 
TG (58:10)           | YNVHIDISXOPRLL-KGNTVBFCSA-N           | 1       | 9545505
TG (58:10)           | GXWBCAVCOMAOHT-VMCJOIRWSA-N    | 1       | 9545277
TG (58:10)           | DILCYSJPEUYFDD-LLFZUAPNSA-N            | 1       | 9545489
TG (58:10)           | JHMNZIPEQPSWIE-XZQOVRJJSA-N           | 0      | 9545278
TG (58:10)           | NZUGCIOVOJPZOH-MDITXENNSA-N        | 0      | 53480554

In the 41598_2017_15231_MOESM1_ESM which is supplementary data for your https://doi.org/10.1038/s41598-017-15231-w, I found that you have selected following 

Chemical   Name | InChIKey                                                  | PubChem CID
TG   (58:10)          | GXWBCAVCOMAOHT-VMCJOIRWSA-N | 9545277

Will you please let me know your criteria for this choice.

**Comment by barupal** [comment]
Hi, 
If you have the MS/MS spectra for this lipid, you can get the acyl chain details. Otherwise, you need to select an approximate ones for the purpose of chemical similarity computation by ChemRICH.

**Comment by ddkale** [comment]
Thank you very much for reply and information.

**Comment by ddkale** [comment]
Hi, I have some lipids (approximately 5 pct of total lipids)  in my data belonging to Di-hexosyl-tri- hydroxy-Ceramides and Mono-lyso-cardiolipins which have not been annotated in PUBCHEM. Do you have some suggestions for how to use these lipids for chemical similarity computation by ChemRICH.

**Comment by barupal** [comment]
You can use PubChem partial name search API = https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/cardiolipin/synonyms/JSON?name_type=word 
Replace "cardiolipin" with any other partial name. But you still need to scroll down the retrieved name list and find your compound.  However, many times compounds are not in PubChem, then you need to draw them in ChemSketch https://www.acdlabs.com/resources/freeware/chemsketch/ and submit to PubChem https://pubchem.ncbi.nlm.nih.gov/upload/#welcome . PubChem will assign the CID and InChiKeys to it.
