### ISSUE TITLE
New Error, Online Tool

### ISSUE THREAD

**Issue by johnsonrk2** [barupal/chemrich#5]
Hello! I'm receiving a new error, using the ChemRICH tool for a different project from before. The error is shown below. Seems to be a problem with the SMILES--I've attached the annotation I'm using and would appreciate any help. Thanks!

![image](https://user-images.githubusercontent.com/16823733/45779576-9895ef00-bc18-11e8-829c-fafa7f171606.png)

[ChemRICH_Anno_GitHub.txt](https://github.com/barupal/chemrich/files/2398643/ChemRICH_Anno_GitHub.txt)

**Comment by barupal** [comment]
Several smiles are incorrect in your file. I used PubChem identifier exchange service to get the correct one. See attached. 
[chemrich_input.txt](https://github.com/barupal/chemrich/files/2398957/chemrich_input.txt)

**Comment by johnsonrk2** [comment]
Thank you @barupal! As a warning to others, it was glitching the day I retrieved them. Probably should have re-done at a later date.
