### ISSUE TITLE
Error message when using ChemRich

### ISSUE THREAD

**Issue by xkcococo** [barupal/chemrich#6]
Greetings,

Thanks for providing this tool!
I am interested in it and want to apply it to my research.
But I have a problem when I tried this demo data, it cannot run successfully. The data I downloaded it from this page as well as the codes I used for this data set.
https://sites.google.com/view/chemrich/predict-correlation-modules

The error message is:
`> chemrich_predict_correlation_modules(inputfile = "/Users/xu.ke/ChemRich/Demo_Data/chemrich_input_correlation_modules.xlsx")
 ..cutHeight not given, setting it to 12.6  ===>  99% of the (truncated) height range in dendro.
 ..done.
Error in data.frame(compound_name = ndf$compound_id, order = sapply(ndf$compound_id,  : 
  arguments imply differing number of rows: 0, 1, 877`

I have no error when I tried other demo data and functions.

Could you help me to figure it out?
Thanks!

**Comment by barupal** [comment]
There was an issue with the column header in the demo excel file. It has been updated. Try the code again using https://github.com/barupal/ChemRICH/blob/master/chemrich_input_correlation_modules.xlsx?raw=true
