### ISSUE TITLE
ChemRICH data analysis error

### ISSUE THREAD

**Issue by geneve1990** [barupal/chemrich#7]
Hello Dinesh,

I am working on a metabolomics data analysis, and am using the ChemRICH to do the enrichment/pathway analysis. For one or two of my dataset, however, I am not able to get the Chemrich Impact Plot. I asked Arpana to help me out, and she referred me to you.  Could you look into this, please? I am attaching the dataset.  

FYI, I did get around 150 metabolites identified, but most of them did not meet the fold change and/or p-value analyses, so I am excluding them, shrinking the dataset down to 23 metabolites. I wonder if I need more than 23 metabolites for ChemRICH to produce the impact plot.  

Thank you,
Tatz

**Comment by barupal** [comment]
ChemRICH input must include all p-values and effect sizes because it uses the distribution of p-values for each chemical set.

**Comment by geneve1990** [comment]
So I have to use the original dataset and include the metabolites that does
not have statistical significance? What if I cannot find InChekeys, SMILES,
or Chem ID for some compounds?

Thank you,
Tatz

**Comment by barupal** [comment]
_So I have to use the original dataset and include the metabolites that does not have statistical significance?_  : correct. 


_What if I cannot find InChekeys, SMILES, or Chem ID for some compounds?_ : 

The Input file must satisfy these conditions 
1. No duplicate names OR CIDs
2. No Missing names, SMILES, pvalue or fold-change
3. Minimum one class with at least three compounds
4. Minimum one class shall be significantly enriched
