### ISSUE TITLE
ChemRICH

### ISSUE THREAD

**Issue by j6granad** [barupal/chemrich#8]
Hi,

I was interested in using ChemRICH, but I ran into some troubles. I got this error when I input my data.

Error replacement has 2 rows, data has 0
In call:
$<-.data.frame(*tmp*,order,value = 1:0)

I saw that a previous issue posted by smweston had a similar issue (https://github.com/barupal/ChemRICH/issues/3). I don't have any negative fold changes, so I think the issue is that there were no significant clusters. Would there be a way to see the associated values for significance?

Best,

Jeff

**Comment by barupal** [comment]
Hi Jeff, 

No significant clusters is one of the reasons that the chemrich script on the web-server can fail. 

Can you re-try [this script]( https://chemrich.idsl.me/predict-mesh-classes ) for your data  ?

**Comment by j6granad** [comment]
Hi!,

The script worked with my data, and I have a file with two new columns (cluster number, xlogP, and meSH class). Thank you! I would really like to get plots like the ones on chemRICH with this. Is there a publication explaining how to interpret this or what the cutoffs for significance are?

**Comment by barupal** [comment]
Great. Now, you can run this [second-script](https://chemrich.idsl.me/run-chemrich/chemical-classes) to get the ChemRICH plot and result table. You can use an adjust _p_-value cutoff of 0.05 for finding significant chemical sets. The ChemRICH plot is created with this cutoff.

**Comment by j6granad** [comment]
After some tinkering with the input file, I thought I had it working, but now I am getting this error. 

> run_chemrich_chemical_classes(inputfile = "MeSh_Prediction_Results.xlsx")
Error in log(clustdf.alt.impact$pvalues) :                                                       
  non-numeric argument to mathematical function

I'm not quite sure what the problem is. Could you please let me know what this might be?

**Comment by barupal** [comment]
It seems the input gave no significant clusters on _p_<0.05. You can change this cutoff in [the script](https://raw.githubusercontent.com/barupal/ChemRICH/master/chemrich_chemical_classes.R) at line    

`clustdf.alt.impact <- clustdf[which(clustdf$pvalues<0.05 & clustdf$csize>1 & clustdf$alteredMetabolites>1) ,]`

**Comment by j6granad** [comment]
Hi! With the raw script, I was able to make it work with some minor tweaks. Thank you so much for your help.
