### ISSUE TITLE
Error message: Subscript out of bounds

### ISSUE THREAD

**Issue by xkcococo** [barupal/chemrich#9]
Greetings,

I am really interested in your tool and want to apply it to my data.
When I copy and paste my data into this website(https://chemrich.fiehnlab.ucdavis.edu/) and try to run Chemrich, I got an error message: 
```
subscript out of bounds
In call:
bitloclist.sb[[x]]
```

Could you help me to solve this issue? 
Thanks in advance!

**Comment by barupal** [comment]
Hi, 
Can you try runing it locally: https://chemrich.idsl.me/predict-mesh-classes
Dinesh

**Comment by xkcococo** [comment]
@barupal 
Thank you! 
I was wondering which codes is the example that I need to use? Because there are many demo data. 
My data has these 6 columns.
Column 1 = Compound Name
Column 2 = InChiKeys
Column 3= Pubchem ID
Column 4 = SMILES
Column 5 = pvalue
Column 6= foldchange

Thanks!
Ke

**Comment by barupal** [comment]
Prepare your data in this format: https://github.com/barupal/ChemRICH/blob/master/chemrich_input_mesh_prediction.xlsx 
Then use below code. 
```
source("https://raw.githubusercontent.com/barupal/ChemRICH/master/predict_mesh_chemical_class.R")
load.ChemRICH.Packages()
predict_mesh_classes(inputfile = "chemrich_input_mesh_prediction.xlsx")
```

**Comment by xkcococo** [comment]
@barupal 
Thank you!
It's really helpful.

But I got this error message when I run this code
`Error in .jnew("org/openscience/cdk/smiles/SmilesParser", get.chem.object.builder()) : 
  Java Exception <no description because toString() failed>get.smiles.parser()new("jobjRef", jobj = <pointer: 0x7fa285c95840>, jclass = "java/lang/Throwable")`

The column has already been changed to the same name and order as the example file.

**Comment by barupal** [comment]
Can you post the input file here ?

**Comment by xkcococo** [comment]
[Book4.xlsx](https://github.com/barupal/ChemRICH/files/6698255/Book4.xlsx)
Thanks for helping!

**Comment by barupal** [comment]
Does this R code work on your computer ? 

`rcdk::parse.smiles("CCCCC")`

The "Book4.xlsx" file is okay and went through the chemrich code on my PC.  It seems like rcdk is having some touble on your computer.

**Comment by xkcococo** [comment]
@barupal 
I can run this code successfully after I installed this package again. Thanks for helping!

**Comment by barupal** [comment]
Glad to know it's is working for you. 

For datasets provided by Metabolon, you can use https://chemrich.idsl.me/run-chemrich/for-metabolons-data

**Comment by xkcococo** [comment]
@barupal 
Thanks! I got an output file from the first codes you provided. But the columns I got is: 
`> colnames(MeSh_Prediction_Results)
[1] "compound_name" "pubchem_id"    "smiles"        "ClusterNumber" "xlogp"        
[6] "MeSH_Class" `
And I saw the demo input has an effect size column. Is it calculated by p.values?
Thanks!
Ke

**Comment by barupal** [comment]
Great. You need to now run this script to get the enrichment statistics - https://chemrich.idsl.me/run-chemrich/chemical-classes There is a different input template for this script. The effect-size and p-values can come from any hypothesis testing statistical method such as the student t-test or KS-test.
